name: Git To Azure repo sync
on: 
  push:
    branches: main
    
jobs:
  sync_from_git_to_azure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment variables
      run: |
        echo "AZUREPAT=${{ secrets.AZUREPAT }}" >> $GITHUB_ENV
        echo "AZUSERNAME=${{ secrets.AZUSERNAME }}" >> $GITHUB_ENV
        echo "AZUSER_EMAIL=${{ secrets.AZUSER_EMAIL }}" >> $GITHUB_ENV
        echo "AZORG=${{ secrets.AZORG }}" >> $GITHUB_ENV
    - name: Clone Git repo
      run: |
        git clone {{repo_url_link}}
        cd repo_name
        rm -rf .git
    - name: Clone Azure Repo
      run: |
        cd ..
        GIT_CMD_REPOSITORY="https://azure-repo-url" 
        git clone $GIT_CMD_REPOSITORY
    - name: Copy files from git repo to azure repo
      run: |     
        cp -r AzureDevops_FOLDER/* GitSyncfolder/
    - name: Configure user in azure repo
      run: |
        cd GitSyncfolder
        git config --global user.email "user_email"
        git config --global user.name "user_email"
    - name: Commit and Push changes
      run: |
        git add .
        git commit -m "sync from git to azure"
        git push
