name: Git To Azure repo sync
on: 
  push:
    branches: main
    
jobs:
  sync_from_git_to_azure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment variables
      run: |
        echo "AZUREPAT=${{ secrets.AZUREPAT }}" >> $GITHUB_ENV
        echo "AZUSERNAME=${{ secrets.AZUSERNAME }}" >> $GITHUB_ENV
        echo "AZUSER_EMAIL=${{ secrets.AZUSER_EMAIL }}" >> $GITHUB_ENV
        echo "AZORG=${{ secrets.AZORG }}" >> $GITHUB_ENV
    - name: Clone Git repo
      run: |
        git clone https://github.com/vaibhav1326/SyncUpGIT-Azure.git
        cd SyncUpGIT-Azure
        rm -rf .git
    - name: Clone Azure Repo
      run: |
        cd ..
        GIT_CMD_REPOSITORY="https://devanshu0986@dev.azure.com/devanshu0986/Vaibhav-Repo/_git/Vaibhav-Repo" 
        git clone $GIT_CMD_REPOSITORY
    - name: Copy files from git repo to azure repo
      run: |     
        cp -r Vaibhav-Repo/* SyncUpGIT-Azure/
    - name: Configure user in azure repo
      run: |
        cd SyncUpGIT-Azure
        git config --global user.email "vaibhavsync@gmail.com"
        git config --global user.name "Vaibhav"
    - name: Commit and Push changes
      run: |
        git add .
        git commit -m "sync from git to azure"
        git push
